apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "7.6.0"
    values:
      # Configuration to use OpenShift Routes
      #
      # Disable NGINX Ingress Controller.
      nginx-ingress:
        enabled: false
      global:
        hosts:
          domain: ${OPENSHIFT_CLUSTER}
        ingress:
          # Unset `spec.ingressClassName` on the Ingress objects
          # so the OpenShift Router takes ownership.
          class: none
          annotations:
            # The OpenShift documentation says "edge" is the default, but
            # the TLS configuration is only passed to the Route if this annotation
            # is manually set.
            route.openshift.io/termination: "edge"
