apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gitlab-operatorgroup.yaml
  - subscription-certmanager.yaml
  - subscription-gitlab.yaml
#  - gitlab.yaml
