apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
spec:
  channel: stable
  name: gitlab-operator-kubernetes
  source: community-operators
  sourceNamespace: openshift-marketplace
